### PR TITLE
:art: add submodule difx-data

### PR DESCRIPTION
**Pull request by shaoguangleo**
Hi @gbcrew , the submodule branch is ready.

Could you please make sure it works for our repo, please see the guide in [submodule uage](https://github.com/difx/difx/wiki/submodule%E2%80%90usage).

Another thing is that, maybe some modification in *test_harness.sh* to point a relative path for the tar file.

### CODE REVIEW

**Comment by gbcrew** [comment]
Not sure how this is supposed to work...but

git pull
git checkout --track origin/feature-submodule
git submodule init 
git submodule update

[gbc@gebeor difx]$ git submodule update
Cloning into '/dat1/DiFX/swc/difx-git/difx/difx-data'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:difx/difx-data' into submodule path '/dat1/DiFX/swc/difx-git/difx/difx-data' failed
Failed to clone 'difx-data'. Retry scheduled
Cloning into '/dat1/DiFX/swc/difx-git/difx/difx-data'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:difx/difx-data' into submodule path '/dat1/DiFX/swc/difx-git/difx/difx-data' failed
Failed to clone 'difx-data' a second time, aborting
[gbc@gebeor difx]$ git branch
  dev
* feature-submodule
  main
[gbc@gebeor difx]$ ls
applications     distclean.sh  index.html    mpifxcorr   setup.bash  tests
CONTRIBUTION.md  doc           install-difx  README.md   setup.csh   utilities
difx-data        genipppc      libraries     README.txt  sites
[gbc@gebeor difx]$ ls difx-data/

So I think there is some permission issue.  After the permission issue is fixed, the merge of the pull request makes this machinery part of 'dev' and then the origin/feature-submodule branch goes away?

**Comment by shaoguangleo** [comment]
This should be the url link issue of submodule. 
I am using the ssh protocol, now I had changed back to https. Then it should work.

You can update using the following command after you are in the *feature-submodule* branch:

```bash
$ git submodule init
$ git submodule update
```

**Comment by gbcrew** [comment]
All of that left .git/config in a strange state with regard to the submodule.  There is probably some command to change the url, but it was easiest just to delete all the submodule info and start over.

I've merged the pull to dev and you (@shaoguangleo ) should probably merge it to main to prevent anyone else from having to go through that.

The submodule semantics is rather confusing as the the top-level git doesn't understand about the submodule even though the submodule .git is there.  That is, it is very easy to confuse yourself...and git is amusingly not as helpful as it usually is.

**Comment by shaoguangleo** [comment]
Thanks @gbcrew for the heads up on the submodule configuration issue.
I appreciate you taking time to fix and merge the branch to dev.
I'll go ahead and merge the PR into main to keep this feature in sync.

**Comment by shaoguangleo** [comment]
I will delete this branch as this issue resolved.
See #23.

**Pull request merged**
