### PR TITLE
Update of Intel IPP include paths + removed invalid free-statement

### PR DESCRIPTION
**Pull request by olaf-b**
Tested for compile OK against Intel compiler suite version 2021.2.0 and IPP version 2021.12.0.

### CODE REVIEW

**Comment by XhrisPhillips** [comment]
I’m not sure how to comment on PRs “properly”. This should not be merged without very careful thought. This may well break everyone else’s setup.

Are you sure that this could not be fixed within genipppc?

Cheers
Chris
________________________________
From: Olaf Trygve Berglihn ***@***.***>
Sent: Saturday, June 29, 2024 12:51:53 AM
To: difx/difx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [difx/difx] Update of Intel IPP include paths + removed invalid free-statement (PR #41)


Tested for compile OK against Intel compiler suite version 2021.2.0 and IPP version 2021.12.0.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/difx/difx/pull/41

Commit Summary

  *   5e63d57<https://github.com/difx/difx/pull/41/commits/5e63d57422672ec24909d0f1d97d71005a9eebad> Removed free of identifier dsIds which is not defined in the given context
  *   0e45b60<https://github.com/difx/difx/pull/41/commits/0e45b60eefa3911ba418f3611f2096505159e521> Updated prefix for IPP includes to match file layout from Intel IPP distribution

File Changes

(11 files<https://github.com/difx/difx/pull/41/files>)

  *   M applications/difx2fits/src/fitsAN.c<https://github.com/difx/difx/pull/41/files#diff-53611ad100790e38b10609dc235fff70eab5d0585c491887e0ed96846ca781e1> (2)
  *   M applications/difx_monitor/mon3d.c<https://github.com/difx/difx/pull/41/files#diff-2789c565d9508cac577d52d25f795fb89fdf67ee02e8284cd823e519a130fbf9> (2)
  *   M applications/difx_monitor/monserver.h<https://github.com/difx/difx/pull/41/files#diff-23dc97672f347dd420e1aee8bf6f57cf86012987c77d8f928bef20ceeb825b9e> (2)
  *   M genipppc<https://github.com/difx/difx/pull/41/files#diff-97c705cba6817b83ad94f4787d5d237a52ae4b3c5d381bf7024f8a7bb42925a5> (2)
  *   M libraries/vdifio/utils/generateVDIF.c<https://github.com/difx/difx/pull/41/files#diff-4c4b32e5c8176c8f10eb4494898d0779fe005603f011368b8b22110663455066> (4)
  *   M libraries/vdifio/utils/vdifLinear2circular.c<https://github.com/difx/difx/pull/41/files#diff-08b3bd6fc733d6f9e12dc946f8a0d12a4e7844b68bdce3dddde0709828196a6a> (4)
  *   M libraries/vdifio/utils/vdifSwapSideband.c<https://github.com/difx/difx/pull/41/files#diff-7087b478adbff84976b9e193a5229d1e19c73d7c1e2a14d56488c4403e12e9fb> (4)
  *   M mpifxcorr/src/architecture.h.gpu.in<https://github.com/difx/difx/pull/41/files#diff-e829af24ae643f7a6e6b157acb7816759460db6d231c89511d39730a2c1a2620> (6)
  *   M mpifxcorr/src/architecture.h.in<https://github.com/difx/difx/pull/41/files#diff-bb32220a53d4118b95151ebfab7c348b3373c6aa8c89422601b11aa248ad2493> (8)
  *   M utilities/fringe_find/fringe_find.cpp<https://github.com/difx/difx/pull/41/files#diff-fc4aea70fb0bd02c45d8bce5f263cff2dfdd5bc22fe5e1f36ecde6521c6ecd1a> (4)
  *   M utilities/fringe_find/fringe_plotDiFX.cpp<https://github.com/difx/difx/pull/41/files#diff-5827bb53073c21e2ebea2e9a864bfeac3f182aedb8cae66f30ada53bc25743ab> (2)

Patch Links:

  *   https://github.com/difx/difx/pull/41.patch
  *   https://github.com/difx/difx/pull/41.diff

**Comment by olaf-b** [comment]
A common convension is to use angle bracket include statements for library headers. Since IPP directory structure where ipp headers are found now has an ipp-prefix i the path - i.e. (...)/oneapi/ipp/latest/include/ipp, and a (...)/latest/ipp.h for backwards compatibility doing a simple chained include of <ipp/ipp.h>, I would argue that include statements using angle brackets should use the prefix: <ipp/ippversion.h>.

**Comment by XhrisPhillips** [comment]
Hi Olaf,

This is not an argument of which is more “right”.  Can you guarantee this will not break compilations for anyone with older versions of IPP?

I don't think this PR should be merged until it has been thoroughly tested by a lot of folk with different setups.

Cheers
Chris
________________________________

**Comment by olaf-b** [comment]
Hi, Chris.  No, I can not make such guarantees.   I expect using <ipp.h> to be backwards compatible, although using <ipp/ipp.h> is the more proper.  I would personally prefer changing the setup and the python introspection and build instructions into either autotools, like most of the code, or CMake.  I will likely do this to get things streamlined with using the _module system_ on our HPC machines for toolchain and library selection.   The free-statement out of context is a bug/misprint, I would argue. Feel free to do as you please with this merge request.  I just make a habit of suggesting improvements/changes whenever I find things that I think should be altered, rather than keeping it in my own drawer only. I agree fully that all merge request should be critically evaluated and thoroughly tested, yes.

**Comment by shaoguangleo** [comment]
Dear @olaf-b , thanks for your PR.

But as @XhrisPhillips mentioned, please ensure that this change do not affect other toolchains across versions.

As stated in our  [contribution guide](https://github.com/difx/difx/wiki/contribution), the `main` branch will no merge this PR unless it is a hotfix for a bug.

I think this PR will be a new feature to support the latest IPP version.
So, could you please push this PR to the `dev` branch?
A developer (at least)  will need to review this change before it can be merged into the `dev` branch.

**Comment by adamdeller** [comment]
Adding my thanks to Olaf for making the contribution - and seconding the request from Shaoguang to change it to be into the dev branch. As mentioned, backwards compatibility with older versions of IPP is quite important and so we will want to confirm that we maintain that while accommodating the changed latest IPP version.

**Comment by olaf-b** [comment]
Hi, Adam. I will close this branch and suggest changes  into the dev branch later as requested. I think the suggestion for changing e.g. include <ipp.h> to <ipp/ippi.h> should be discarded, and rather one should use only "ipp.h".  This will chain-load sub-headers and be backwards compatible.  But first I want to test my replacement of the setup.{bash,csh}, install-difx and genipppc using conventional autotools.  This will better allow me to integrate with the module system without requiring manual configuration, and also give a more common compile and install process using

``` 
./configure --prefix=<prefix path> \
  --with-ipp-includes=<path> --with-ipp-libdir=<path> \
   --enable-<feature> <...>  &&
   make  &&
   make install
```

**Pull request closed without merging**
