### PR TITLE
Update guide for user and developers

### PR DESCRIPTION
**Pull request by shaoguangleo**
Hi @adamdeller , I add some introduction for the user (stable version) and developer (git-flow).
Please have a look on this.

### CODE REVIEW

**Comment by adamdeller** [comment]
Hey @shaoguangleo , looks good. The only thing I wondered was about forking the repo - that wasn't something that I did, for instance. Do we want to insist (or at least insistently suggest) that people fork the repo?  Or should that step be optional?

**Comment by shaoguangleo** [comment]
Hi @adamdeller , you raise a good point.
Forking the repository is not strictly required before cloning, so you're right, it's optionally.
The main benefits of forking are:
- It allows the user (beside DiFX devs) to easily make chanages and open PR back to the main repo. Without forking, pushing changes requires extra permissions(currently only DiFX dev can do this)
- This will keep the clone synced with the upstream repo, can also done with `remote` command.

So, I will add some more instructions.
Please let me know if you have any other suggestions.

**Comment by adamdeller** [comment]
I've further updated the documentation to encourage people to join difx-developers and work directly in the DiFX project, but to show how forks can be used if desired. If you're happy with it, please merge the PR.

**Comment by shaoguangleo** [comment]
These changes look good to me.

**Comment by jwagnerhki** [comment]
Could you, @shaoguangleo, perhaps also add some info regarding git-flow? 
In particular, what to use for git flow init? Might the below settings be correct?

```
[difx@fxmanager git]$ git flow init
Which branch should be used for bringing forth production releases?
Branch name for production releases: [main] main
Which branch should be used for integration of the "next release"?
Branch name for "next release" development: [develop] origin/dev
How to name your supporting branch prefixes?
Feature branches? [feature/]
Release branches? [release/]
Hotfix branches? [hotfix/]
Support branches? [support/]
Version tag prefix? []
```

**Comment by jwagnerhki** [comment]
Or hmm now that several existing branches are named "hotfix-*", maybe the git flow init settings would have a "-" rather than "/" as part of the prefix, e.g.
```
Feature branches? [feature/] feature-
Release branches? [release/] release-
Hotfix branches? [hotfix/] hotfix-
Support branches? [support/] support-
Version tag prefix? []
```

**Comment by shaoguangleo** [comment]
Hi @jwagnerhki , thanks for your feedback.
The `hotfix-` branch is the easiest way to migrate all the trunk source code here.
So the rules you mentioned also no problem.

There are some initial steps for our developers, https://github.com/difx/difx/wiki/contribution and https://github.com/difx/difx/wiki/Double%E2%80%90check-Hotfix-example.
Hope this help.

**Pull request merged**
